# Generated by Django 4.1.7 on 2023-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=100)),
                ('userTitle', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=15)),
                ('dateofBirth', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postalcode', models.CharField(blank=True, max_length=12)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=250)),
                ('picture', models.ImageField(blank=True, upload_to='profile/')),
                ('Description', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(default='')),
                ('status', models.BooleanField(default=False)),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'signupUser',
                'verbose_name_plural': 'New User',
            },
        ),
    ]
