# Generated by Django 4.1.7 on 2023-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='mobile',
            field=models.CharField(blank=True, default='000 00000 000000', max_length=15),
        ),
    ]
